
#Data Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coa_travel_management
    username: coa_team1
    password: coa_team1

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: TRUE


logging:
  level:
    org:
      springframework:
      # web:DEBUG
        jdbc:
          core: TRACE
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE



server:
  port: 8010
  servlet:
    context-path: /coa

